package br.com.guialves.rflr.datastructure;

import java.util.concurrent.ThreadLocalRandom;

/**
 * Flat-array segment tree for sum queries and priority-proportional sampling.
 * (This class was almost entirely generated by AI, the focus is just to show this as an alternative).
 * <p>
 * Layout (1-indexed, size rounded up to next power of 2):
 * <p>
 *          tree[1]          ← root
 *         /       \
 *     tree[2]   tree[3]
 *     /   \     /   \
 *   [4]  [5] [6]  [7]      ← internal nodes
 *   [8][9][10][11][12]...  ← leaves start at tree[capacity]
 * <p>
 *   parent(i)      = i >> 1
 *   leftChild(i)   = i << 1
 *   rightChild(i)  = i << 1 | 1
 * <p>
 * Implementation based on:
 *  <a href="https://www.youtube.com/watch?v=QvgpIX4_vyA&t=70s">AlgorithmsThread 3: Segment Trees</a>
 *  <a href="https://github.com/Curt-Park/rainbow-is-all-you-need/blob/master/03_per.py">Rainbow is All You Need</a>
 */
public class SumSegmentTreeFlat implements ISumSegmentTree {

    private final int size;
    private final int capacity; // next power of 2 >= size
    private final float[] tree; // size 2 * capacity

    public SumSegmentTreeFlat(int size, float initValue) {
        this.size = size;
        this.capacity = nextPowerOfTwo(size);
        this.tree = new float[2 * capacity];

        for (int i = capacity; i < capacity + size; i++) {
            tree[i] = initValue;
        }

        for (int i = capacity - 1; i >= 1; i--) {
            tree[i] = tree[i << 1] + tree[i << 1 | 1];
        }
    }

    public SumSegmentTreeFlat(float[] array) {
        this.size = array.length;
        this.capacity = nextPowerOfTwo(array.length);
        this.tree = new float[2 * capacity];

        System.arraycopy(array, 0, tree, capacity, array.length);

        for (int i = capacity - 1; i >= 1; i--) {
            tree[i] = tree[i << 1] + tree[i << 1 | 1];
        }
    }

    @Override
    public int size() {
        return size;
    }

    @Override
    public float sum() {
        return tree[1];
    }

    /**
     * Updates the value at position idx and propagates the change up to the root.
     * O(log n).
     */
    @Override
    public void update(int idx, float value) {
        if (idx < 0 || idx >= size) return;

        int i = capacity + idx;
        tree[i] = value;

        // propagate the new sum upward
        i >>= 1;
        while (i >= 1) {
            tree[i] = tree[i << 1] + tree[i << 1 | 1];
            i >>= 1;
        }
    }

    /**
     * Returns the sum of elements in the range [start, end] inclusive.
     * O(log n).
     */
    @Override
    public float rangeSum(int start, int end) {
        if (start > end) return 0;
        start = Math.max(start, 0);
        end = Math.min(end, size - 1);
        if (start > end) return 0;

        float result = 0;
        int left = capacity + start;
        int right = capacity + end;

        while (left <= right) {
            if ((left & 1) == 1) result += tree[left++];   // left is a right child; accumulate and move forward
            if ((right & 1) == 0) result += tree[right--]; // right is a left child; accumulate and move back
            left >>= 1;
            right >>= 1;
        }

        return result;
    }

    /**
     * Returns the cumulative sum from index 0 to end inclusive.
     * Equivalent to np.cumsum(array)[end].
     * O(log n).
     */
    @Override
    public float prefixSum(int end) {
        return rangeSum(0, end);
    }

    /**
     * Draws a random sample in [lower, upper) and returns the corresponding index
     * under the priority-proportional distribution (lower bound on the prefix sum).
     * O(log n).
     */
    @Override
    public int sampleIndexByValueInRange(float lower, float upper) {
        float totalSum = sum();
        if (lower < 0) throw new IllegalArgumentException("lower cannot be negative: " + lower);
        if (upper > totalSum) throw new IllegalArgumentException("upper cannot exceed total sum. upper: " + upper + ", total: " + totalSum);
        if (lower >= upper) throw new IllegalArgumentException("lower must be < upper. lower: " + lower + ", upper: " + upper);

        float sample = ThreadLocalRandom.current().nextFloat(lower, upper);
        return sampleIndexByValue(sample);
    }

    /**
     * Lower bound on the prefix sum: returns the smallest index k such that prefixSum(k) >= sample.
     * Descends the tree by comparing against the left child sum at each level.
     * O(log n).
     */
    private int sampleIndexByValue(float sample) {
        int i = 1; // start at root

        while (i < capacity) {
            int left = i << 1;
            if (sample <= tree[left]) {
                i = left;
            } else {
                sample -= tree[left];
                i = left | 1;
            }
        }

        return i - capacity; // convert tree index → array index
    }

    private static int nextPowerOfTwo(int n) {
        if (n <= 1) return 1;
        return Integer.highestOneBit(n - 1) << 1;
    }
}
