package br.com.guialves.rflr.djlutils;

import ai.djl.Device;
import ai.djl.Model;
import ai.djl.ndarray.BaseNDManager;
import ai.djl.ndarray.NDArray;
import ai.djl.ndarray.NDList;
import ai.djl.ndarray.NDManager;
import ai.djl.nn.Block;
import ai.djl.training.ParameterStore;
import lombok.Cleanup;
import lombok.SneakyThrows;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.concurrent.ConcurrentHashMap;
import java.util.function.*;

import static br.com.guialves.rflr.djlutils.DJLUtils.AXIS_EMPTY;
import static br.com.guialves.rflr.djlutils.DJLUtils.FIRST_POS;
import static java.util.stream.Collectors.*;

public class DJLMemoryManagement {

    public static final int NOT_FOUND_COUNT = -1;

    private DJLMemoryManagement() {
        throw new IllegalStateException("No DJLMemoryManagement!");
    }

    public static void release(NDArray input) {
        if (input != null) input.close();
    }

    public static void release(NDArray inputA, NDArray inputB) {
        if (inputA != null) inputA.close();
        if (inputB != null) inputB.close();
    }

    public static void release(NDArray... arrays) {
        for (var array : arrays) {
            if (array != null) array.close();
        }
    }

    /**
     * Close and set null in each element to avoid memory leaks.
     * @param arrays Each element will be closed and null set
     */
    @SneakyThrows
    public static void release(AutoCloseable[] arrays) {
        for (int i = 0; i < arrays.length; ++i) {
            if (arrays[i] != null) arrays[i].close();
            arrays[i] = null;
        }
    }

    public static NDArray transfer(NDManager manager, NDArray oldVal, NDArray newVal) {
        oldVal.close();
        newVal.attach(manager);
        return newVal;
    }

    public static NDArray scoped(final UnaryOperator<NDArray> block,
                                 final NDArray input) {
        @Cleanup var sub = subMgr(input, "scoped-input");
        input.tempAttach(sub);
        var result = block.apply(input);
        if (result == input) {
            throw new IllegalStateException("scoped block returned the input NDArray itself");
        }

        return sub.ret(result);
    }

    /**
     * Method used when we are going to execute all operations inside the block
     * and release all components except input of the memory (the release
     * is decided by the caller). One example is when we want to return
     * a primitive or on-heap Java object.
     * @param sub Sub NDManager that has short time span
     * @param block Lambda block where the custom code will be executed
     * @param input Input data
     * @return Output generated by the lambda block
     */
    private static NDArray scopedNotReturned(final NDManager sub,
                                             final UnaryOperator<NDArray> block,
                                             final NDArray input) {
        input.tempAttach(sub);
        var result = block.apply(input);
        if (result == input) {
            throw new IllegalStateException("scoped block returned the input NDArray itself");
        }

        return result;
    }

    public static float scopedToFloat(final UnaryOperator<NDArray> block,
                                      final NDArray input) {
        @Cleanup var sub = subMgr(input, "scoped-o-f");
        var out = scopedNotReturned(sub, block, input);
        return out.getFloat(AXIS_EMPTY);
    }

    public static long scopedToFirstLong(final UnaryOperator<NDArray> block,
                                          final NDArray input) {
        @Cleanup var sub = subMgr(input, "scoped-o-l");
        var out = scopedNotReturned(sub, block, input);
        return out.getLong(FIRST_POS);
    }

    public static NDArray scoped(final BinaryOperator<NDArray> block,
                                 final NDArray inputA,
                                 final NDArray inputB) {
        if (inputA.getManager() != inputB.getManager()) {
            throw new IllegalArgumentException("scoped inputs must belong to the same NDManager");
        }

        @Cleanup var sub = subMgr(inputA, "scoped-a-b");
        inputA.tempAttach(sub);
        inputB.tempAttach(sub);

        var result = sub.ret(block.apply(inputA, inputB));
        if (result == inputA || result == inputB) {
            throw new IllegalStateException("scoped block returned any input NDArray itself");
        }
        return result;
    }

    public static NDArray scoped(final Function<NDArray[], NDArray> block,
                                 final NDArray... arrays) {
        if (arrays.length == 0) throw new IllegalArgumentException("arrays must contain elements!");

        @Cleanup var sub = subMgr(arrays[0], "scoped-arrays");
        sub.tempAttachAll(arrays);

        var result = sub.ret(block.apply(arrays));
        for (var element : arrays) {
            if (element == result) {
                throw new IllegalStateException("scoped block returned any input NDArray itself");
            }
        }

        return result;
    }

    public static NDArray scoped(final BiFunction<NDArray, NDArray[], NDArray> block,
                                 final NDArray input,
                                 final NDArray... arrays) {
        if (arrays.length == 0) throw new IllegalArgumentException("arrays must contain elements!");

        @Cleanup var sub = subMgr(arrays[0], "scoped-a-arrays");
        input.tempAttach(sub);
        sub.tempAttachAll(arrays);

        var result = sub.ret(block.apply(input, arrays));
        for (var element : arrays) {
            if (element == result) {
                throw new IllegalStateException("scoped block returned any input NDArray itself");
            }
        }

        return result;
    }

    public static NDList safeForwardSingle(NDManager manager,
                                           Block block,
                                           ParameterStore parameterStore,
                                           NDList inputs,
                                           boolean training) {
        if (inputs.size() != 1) throw new IllegalArgumentException("The network just accepts one head input!");
        @Cleanup var sub = subMgr(manager, "safe-forward-single");
        inputs.getFirst().tempAttach(sub);
        var output = block.forward(parameterStore, inputs, training);
        output.attach(manager);
        return output;
    }

    public static void debugDump(NDManager manager) {
        var root = getDebugDump(manager);
        if (root.isEmpty()) {
            IO.println("NDManager is not a BaseNDManager: " + manager.getClass());
            return;
        }
        IO.println("Debug dump NDManager:");
        printTree(root.get(), 0);
    }

    /**
     * Builds a hierarchical snapshot of an {@link NDManager}'s resource tree.
     *
     * <p>The returned tree is a value object built via reflection on DJL's
     * {@code BaseNDManager.resources} map. Each node describes a single
     * manager; nested sub-managers appear as children. The snapshot is
     * taken at call time and is decoupled from the live manager, so the
     * structure is safe to traverse, filter, count and assert against
     * without holding any reference to the underlying resources.</p>
     *
     * <p>Designed to power two use cases:
     * <ul>
     *   <li>Human-friendly printing via {@link #debugDump(NDManager)};</li>
     *   <li>Structural assertions in regression tests, e.g.
     *       {@code findLeakingNodes(root, 100)} to locate the sub-managers
     *       that accumulate resources during a training step.</li>
     * </ul>
     *
     * @param manager the root manager to inspect (typically the system
     *                manager, an agent's parent, or a specific sub-manager)
     * @return a {@link ManagerNode} describing the full hierarchy, or
     *         {@link Optional#empty()} if the manager is not a
     *         {@code BaseNDManager} (which means the reflection probe
     *         cannot run, and we refuse to fabricate a partial tree)
     */
    @SneakyThrows
    @SuppressWarnings("unchecked")
    public static Optional<ManagerNode> getDebugDump(NDManager manager) {
        if (!(manager instanceof BaseNDManager base)) {
            return Optional.empty();
        }

        var uidField = BaseNDManager.class.getDeclaredField("uid");
        uidField.setAccessible(true);
        var resourcesField = BaseNDManager.class.getDeclaredField("resources");
        resourcesField.setAccessible(true);

        var uid = (String) uidField.get(base);
        var resources = (ConcurrentHashMap<String, AutoCloseable>) resourcesField.get(base);

        var byType = resources.values().stream()
                .collect(groupingBy(
                        resource -> resource == null
                                ? "null"
                                : resource.getClass().getSimpleName(),
                        counting()));

        var children = new ArrayList<ManagerNode>();
        for (var element : resources.values()) {
            if (element instanceof BaseNDManager innerBase) {
                var child = getDebugDump(innerBase);
                child.ifPresent(children::add);
            }
        }

        return Optional.of(new ManagerNode(
                manager.getName(),
                uid,
                manager.isOpen(),
                resources.size(),
                byType,
                List.copyOf(children)
        ));
    }

    private static void printTree(ManagerNode node, int level) {
        var sb = new StringBuilder(160);
        sb.repeat("    ", Math.max(0, level));
        sb.append("\\--- NDManager[").append(node.name())
                .append(" | uid=").append(node.uid())
                .append("] resources=").append(node.totalResources());
        if (!node.byType().isEmpty()) {
            sb.append(" {").append(node.byType().entrySet().stream()
                            .map(e -> e.getKey() + "=" + e.getValue())
                            .sorted()
                            .collect(joining(", ")))
                    .append("}");
        }
        IO.println(sb);
        for (var child : node.children()) {
            printTree(child, level + 1);
        }
    }

    public static int managedArrayCount(NDManager manager) {
        if (manager instanceof BaseNDManager base) {
            return base.getManagedArrays().size();
        }

        return NOT_FOUND_COUNT;
    }

    /**
     * Recursively counts the total number of resources (NDArrays + sub-NDManagers)
     * in the entire manager hierarchy, starting from the base manager.
     *
     * <p>Designed for memory leak detection in tests. The count should be stable
     * across runs of the same operation when no leak is present. A growing count
     * indicates that one or more arrays/managers are not being closed properly.</p>
     *
     * <p>Counts every entry in the {@code resources} map of every manager in the
     * tree, including both NDArrays and child NDManagers. The base manager's own
     * state (engine-related resources) is included.</p>
     *
     * @return the total resource count across the whole hierarchy, or {@code -1 (NOT_FOUND_COUNT)}
     *         if the count cannot be measured (e.g. due to reflection failures
     *         on an incompatible DJL version)
     */
    public static int systemResourceCount(NDManager manager) {
        try {
            return getDebugDump(manager)
                    .map(ManagerNode::subtreeSize)
                    .orElse(NOT_FOUND_COUNT);
        } catch (Exception e) {
            return NOT_FOUND_COUNT;
        }
    }

    /**
     * Immutable snapshot of one node in an {@link NDManager} hierarchy.
     *
     * <p>Built by {@link DJLMemoryManagement#getDebugDump(NDManager)} via
     * reflection on {@code BaseNDManager.resources}. Use the static
     * helpers on {@link DJLMemoryManagement} to query the tree
     * ({@code findByName}, {@code findByNamePrefix}, {@code findLeakingNodes},
     * {@code subtreeSize}).</p>
     *
     * @param name           the manager's debug name
     * @param uid            unique id of the manager (from reflection)
     * @param open           whether the manager was open at snapshot time
     * @param totalResources direct resource count (own NDArrays + own sub-managers)
     * @param byType         resource count grouped by simple class name
     * @param children       nested sub-managers (recursively built)
     */
    public record ManagerNode(String name,
                              String uid,
                              boolean open,
                              int totalResources,
                              Map<String, Long> byType,
                              List<ManagerNode> children) {
        /**
         * Total resources across the whole subtree rooted at this node,
         * including direct resources and every nested child recursively.
         */
        public int subtreeSize() {
            int total = totalResources;
            for (var child : children) {
                total += child.subtreeSize();
            }
            return total;
        }

        /**
         * Finds the first node (pre-order) whose name equals the given value.
         *
         * @return the first matching node, or empty if none
         */
        public Optional<ManagerNode> findByName(String target) {
            if (name.equals(target)) return Optional.of(this);
            for (var child : children) {
                var hit = child.findByName(target);
                if (hit.isPresent()) return hit;
            }
            return Optional.empty();
        }

        /**
         * Finds the first node (pre-order) whose name starts with the given prefix.
         * Useful to locate all managers tagged with a given label
         * (e.g. {@code "ExperienceReplayBuffer-"}, {@code "DeepQNetworkMLP-"}).
         */
        public Optional<ManagerNode> findByNamePrefix(String prefix) {
            if (name.startsWith(prefix)) return Optional.of(this);
            for (var child : children) {
                var hit = child.findByNamePrefix(prefix);
                if (hit.isPresent()) return hit;
            }
            return Optional.empty();
        }

        /**
         * Collects every node (pre-order) whose own {@code totalResources}
         * is greater than the given threshold. The threshold is interpreted
         * as a direct count, not a subtree size.
         */
        public List<ManagerNode> findLeakingNodes(long threshold) {
            return findMatching(n -> n.totalResources > threshold);
        }

        /**
         * Collects every node (pre-order) that satisfies the given predicate.
         */
        public List<ManagerNode> findMatching(Predicate<ManagerNode> predicate) {
            var hits = new ArrayList<ManagerNode>();
            if (predicate.test(this)) hits.add(this);
            for (var child : children) {
                hits.addAll(child.findMatching(predicate));
            }
            return hits;
        }
    }

    public static NDManager cappedParentMgr(Device device) {
        var parent = NDManager.newBaseManager(device);
        parent.setName("parent-" + parent.getName());
        parent.cap();
        return parent;
    }

    public static NDManager setName(NDManager mgr, String name) {
        mgr.setName(name + "-" + mgr.getName());
        return mgr;
    }

    public static NDArray setName(NDArray array, String name) {
        array.setName(name + "-" + array.getName());
        return array;
    }

    public static NDManager subMgr(NDArray array, String name) {
        return subMgr(array.getManager(), name);
    }

    public static NDManager subMgr(NDManager manager, Class<?> clazz) {
        return subMgr(manager, clazz.getSimpleName());
    }

    public static NDManager subMgr(NDManager manager, String name) {
        var sub = manager.newSubManager();
        sub.setName(name + "-" + sub.getName());
        return sub;
    }

    public static Model newModel(Class<?> clazz) {
        return newModel(clazz.getSimpleName(), null);
    }

    public static Model newModel(String name) {
        return newModel(name, null);
    }

    public static Model newModel(Class<?> clazz, Device device) {
        return newModel(clazz.getSimpleName(), device);
    }

    public static Model newModel(String name, Device device) {
        var model = Model.newInstance(name, device);
        var mgr = model.getNDManager();
        mgr.setName(name + "-" + mgr.getName());
        return model;
    }
}
